### ISSUE TITLE
Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.2.1

### ISSUE THREAD

**Issue by roozbehid-ic** [praeclarum/Ooui#126]
When I build the project, I get this error 

    System.IO.FileNotFoundException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.2.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. File name: 'System.Diagnostics.DiagnosticSource, Version=4.0.2.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' at WebApplication2.Program.BuildWebHost

I started with Visual Studio 2017 15.6.5, choose ASP .Net Core MVC application type and followed this guide : https://montemagno.com/building-a-xaml-xamarin-forms-asp-net-website/

My csproj is  

    <Project Sdk="Microsoft.NET.Sdk.Web">
    
      <PropertyGroup>
        <TargetFramework>netcoreapp2.0</TargetFramework>
       <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
      </PropertyGroup>
    
      <ItemGroup>
        <EmbeddedResource Remove="Page.xaml" />
      </ItemGroup>
    
      <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore" Version="2.0.2" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.0.2" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Formatters.Json" Version="2.0.2" />
        <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.0.2" />
        <PackageReference Include="Ooui" Version="0.9.206" />
        <PackageReference Include="Ooui.AspNetCore" Version="0.9.206" />
        <PackageReference Include="Ooui.Forms" Version="0.9.206" />
        <PackageReference Include="Ooui.Wasm" Version="0.9.206" />
        <PackageReference Include="Xamarin.Forms" Version="3.0.0.296286-pre2" />
      </ItemGroup>
    
      <ItemGroup>
        <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.3" />
      </ItemGroup>
    
      <ItemGroup>
        <PropertyPageSchema Remove="Page.xaml" />
      </ItemGroup>
    
      <ItemGroup>
        <Page Include="Page.xaml">
          <Generator>MSBuild:Compile</Generator>
        </Page>
      </ItemGroup>
    
      <ItemGroup>
        <EmbeddedResource Update="Page1.xaml">
          <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
        </EmbeddedResource>
      </ItemGroup>
    
    </Project>

The rest is all defaults. No changes to anything. Though when doing dotnet build I also get these warnings :

    C:\Users\rg\.nuget\packages\ooui.wasm\0.9.206\build\netstandard2.0\Ooui.Wasm.targets(17,3): warning : Failed to resolve type System.IO.Stream 
    [c:\users\rg\source\repos\WebApplication2\WebApplication2\WebApplication2.csproj] C:\Users\rg\.nuget\packages\ooui.wasm\0.9.206\build\netstandard2.0\Ooui.Wasm.targets(17,3): warning : Failed to resolve type System.IO.Stream 
    [c:\users\rg\source\repos\WebApplication2\WebApplication2\WebApplication2.csproj]
    C:\Users\rg\.nuget\packages\ooui.wasm\0.9.206\build\netstandard2.0\Ooui.Wasm.targets(17,3): warning : Failed to resolve method System.Void System.Security.UnverifiableCodeAttribute::.ctor() [c:\users\rg\source\repos\WebApplication2\WebApplication2\WebApplication2.csproj]

**Comment by roozbehid-ic** [comment]
Ok. I fixed this error by upgrading everything to 2.1.0-preview1-final
But now this is what I am getting

    description: "Memory index is out of range"
    message: "Memory index is out of range"
    number: -2146821271
    stack: "RuntimeError: Memory index is out of range at Module[_mono_wasm_invoke_method] (file:///c:/Users/r.g/source/repos/WebApplication2/WebApplication2/bin/Debug/netcoreapp2.0/dist/mono.js:1:163875) at MonoRuntime.call_method (file:///c:/Users/r.g/source/repos/WebApplication2/WebApplication2/bin/Debug/netcoreapp2.0/dist/ooui.js:401:9) at WebAssemblyApp.runApp (file:///c:/Users/rg/source/repos/WebApplication2/WebApplication2/bin/Debug/netcoreapp2.0/dist/ooui.js:434:13) at WebAssemblyApp.init (file:///c:/Users/r.g/source/repos/WebApplication2/WebApplication2/bin/Debug/netcoreapp2.0/dist/ooui.js:423:9) at MonoRuntime.init (file:///c:/Users/r.g/source/repos/WebApplication2/WebApplication2/bin/Debug/netcoreapp2.0/dist/ooui.js:381:9) at Module.bclLoadingDone (file:///c:/Users/r.g/source/repos/WebApplication2/WebApplication2/bin/Debug/netcoreapp2.0/dist/ooui.js:363:9) at Anonymous function (file:///c:/Users/r.g/source/repos/WebApplication2/WebApplication2/bin/Debug/netcoreapp2.0/dist/ooui.js:356:21)"

**Comment by yowl** [comment]
How about these instructions: https://github.com/praeclarum/Ooui/wiki/Xamarin.Forms-with-Web-Assembly
